name = "formulaforge-web"
compatibility_date = "2024-01-01"

[env.production]
name = "formulaforge-web"

[env.preview]
name = "formulaforge-web-preview"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "bun run build"
cwd = "."

# Environment variables (add your actual values)
[vars]
# Add any environment variables your app needs here
# NODE_ENV = "production"
